In [1]:
import torch
import numpy as np

In [8]:
def f(x):
    return 3*x**2-4*x

In [9]:
def numerical_limit(f, x, h):
    return ((f(x+h)-f(x))/h)

In [11]:
h=0.1
for i in range(6):
    print(f'h={h:.6f}, numerical limit={numerical_limit(f, 1, h): .6f}')
    h= h*0.1

h=0.100000, numerical limit= 2.300000
h=0.010000, numerical limit= 2.030000
h=0.001000, numerical limit= 2.003000
h=0.000100, numerical limit= 2.000300
h=0.000010, numerical limit= 2.000030
h=0.000001, numerical limit= 2.000003


In [22]:
x= torch.arange(5.0, requires_grad=True)

In [23]:
x

tensor([0., 1., 2., 3., 4.], requires_grad=True)

In [24]:
print(x.grad)

None


In [25]:
y= torch.dot(x,x)

In [26]:
y

tensor(30., grad_fn=<DotBackward0>)

In [27]:
y.backward()

In [29]:
x.grad

tensor([0., 2., 4., 6., 8.])

In [30]:
# pytorch accumulates the gradient by default, we need to clear th previous values

In [31]:
x.grad.zero_()

tensor([0., 0., 0., 0., 0.])

In [33]:
x.grad

tensor([0., 0., 0., 0., 0.])

In [35]:
y= torch.dot(x,x)
y.backward()
print(x.grad)

tensor([0., 2., 4., 6., 8.])


Backward for non-scaler variable

In [36]:
x= torch.arange(3.0, requires_grad=True)
y= x*x

y.backward(torch.tensor([1.0, 1.0, 1.0])) #since the output should be vector
print(x.grad)

tensor([0., 2., 4.])


In [37]:
x= torch.arange(3.0, requires_grad=True)
y= x*x

y.backward(torch.tensor([1.0, 1.0, 0.0])) #since the output should be vector
print(x.grad)

tensor([0., 2., 0.])


more example

In [40]:
a= torch.tensor([2., 3.], requires_grad=True)
b= torch.tensor([6., 4.], requires_grad=True)

In [41]:
Q= 3*a**3- b**2

In [44]:
print(a.grad)
print(b.grad)

None
None


In [45]:
external_grad= torch.tensor([1,1])
Q.backward(gradient=external_grad)

In [46]:
print(a.grad)
print(b.grad)

tensor([36., 81.])
tensor([-12.,  -8.])


In [23]:
import torch

x= torch.tensor([1.0,2.0,3.0,4.0], requires_grad=True)
y= torch.tensor([5.0,6.0,7.0,8.0], requires_grad=True)
z= x*y
loss= z.sum()
print(z.grad)

None


C:\Users\AIXI\AppData\Local\Temp\ipykernel_1496\2869603445.py:7: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\cb\pytorch_1000000000000\work\build\aten\src\ATen/core/TensorBody.h:491.)
  print(z.grad)


In [24]:
loss.backward()
print(x.grad)  #dz/dx
print(y.grad)   #dz/dy

tensor([5., 6., 7., 8.])
tensor([1., 2., 3., 4.])


In [2]:
nx= torch.arange(1,20, 3, dtype=float)
print(nx)

tensor([ 1.,  4.,  7., 10., 13., 16., 19.], dtype=torch.float64)
