In [1]:
import torch

# 1. Creating Tensors
tensor_from_list = torch.tensor([1, 2, 3])  # From a Python list
tensor_from_array = torch.tensor([[4, 5], [6, 7]])  # 2D tensor from a nested list
zero_tensor = torch.zeros((2, 3))  # 2x3 tensor filled with zeros
one_tensor = torch.ones((3, 3))  # 3x3 tensor filled with ones
rand_tensor = torch.rand((2, 2))  # 2x2 tensor with random values

In [18]:
print(torch.tensor([113]))
# print(torch.tensor(12).shape)

tensor([113])


In [36]:
# creating a 1d tensor(also called vector)
tensor_1d= torch.tensor([12, 123, 45])
print(tensor_1d)
print(tensor_1d.shape)
# torch.Size([3]) means the tensor is one-dimensional with a length of 3 elements.

tensor([ 12, 123,  45])
torch.Size([3])


In [37]:
# creating 2d tensor
tensor_2d= torch.tensor(([1,2,3], [4,5,6]))
print(tensor_2d)

tensor_2dd= torch.tensor([[1,2,3],[4,5,6]])
print(tensor_2dd)
print(tensor_2dd.shape)
# torch.Size([2, 3]) indicates that the tensor is two-dimensional with 2 rows and 3 columns

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


dimensionality of a tensor in PyTorch refers to the levels of nested lists used to create it, not just the number of rows or elements.

In [38]:
# creating 3 3d tensor
tensor_3d= torch.tensor([[1,2,3,4],[5,6,7,8],[33,22,11,44]])
print(tensor_3d)
print(tensor_3d.shape)
# torch.Size([3, 4]) means the tensor is two-dimensional with 3 rows and 4 columns.

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [33, 22, 11, 44]])
torch.Size([3, 4])


In [41]:
tensor_3d= torch.tensor([[1,2,3,4],[5,6,7,8],[33,22,11,44]])
print(tensor_3d)
print(tensor_3d.shape)

# In this example, tensor_3d is a 3D tensor with the shape [1, 3, 4], which means
# it has 1 layer (or depth) that contains a 3x4 matrix. The extra pair of brackets [[]] around
# the original lists adds another dimension.

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [33, 22, 11, 44]])
torch.Size([3, 4])


In [54]:
# dimtensor= torch.tensor([[[1,2], [6,6],[44,22]], [[1,2], [6,6],[44,22]], [[1], [6,6],[44,22]]])
# dimtensor= torch.tensor([[[1,2], [6,6],[44,22]], [[2,5], [6,6],[44,22]]])
dimtensor= torch.tensor([[[1,2], [6,6],[44,22]], [[6,6],[44,22]]])
print(dimtensor.shape)

ValueError: expected sequence of length 3 at dim 1 (got 2)

In [5]:
print(tensor_from_list.shape)
print(tensor_from_array.shape)
print(rand_tensor.shape)

torch.Size([3])
torch.Size([2, 2])
torch.Size([2, 2])


torch.Size([3])

In [ ]:
import torch

# 1. Creating Tensors
tensor_from_list = torch.tensor([1, 2, 3])  # From a Python list
tensor_from_array = torch.tensor([[4, 5], [6, 7]])  # 2D tensor from a nested list
zero_tensor = torch.zeros((2, 3))  # 2x3 tensor filled with zeros
one_tensor = torch.ones((3, 3))  # 3x3 tensor filled with ones
rand_tensor = torch.rand((2, 2))  # 2x2 tensor with random values

# 2. Basic Tensor Operations
added_tensor = tensor_from_list + tensor_from_list  # Element-wise addition
mul_tensor = tensor_from_list * 2  # Element-wise multiplication
reshaped_tensor = tensor_from_array.view(4)  # Reshaping tensor to 1D

# Displaying tensors
print("Created Tensors:")
print("From List:", tensor_from_list)
print("2D Tensor:", tensor_from_array)
print("Zeros:", zero_tensor)
print("Ones:", one_tensor)
print("Random:", rand_tensor)
print("\nBasic Operations:")
print("Added Tensor:", added_tensor)
print("Multiplied Tensor:", mul_tensor)
print("Reshaped Tensor:", reshaped_tensor)
